const express = require('express');
const fs = require('fs');
const path = require('path');
const { GoogleGenAI } = require('@google/genai');
const { authOptional } = require('../middleware/auth');

const router = express.Router();

// ---- Multi API key rotation ----
// Set GEMINI_API_KEYS as a comma-separated list in .env for automatic failover.
// Get a free key (no credit card required) at https://aistudio.google.com/apikey
const rawKeys = (process.env.GEMINI_API_KEYS || process.env.GEMINI_API_KEY || '')
  .split(',')
  .map((k) => k.trim())
  .filter(Boolean);

let keyIndex = 0;
function nextClient() {
  if (rawKeys.length === 0) return null;
  const key = rawKeys[keyIndex % rawKeys.length];
  return new GoogleGenAI({ apiKey: key });
}

const GEMINI_MODEL = process.env.GEMINI_MODEL || 'gemini-3.5-flash-lite'; // free tier stable model

function getMimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg';
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  if (ext === '.heic') return 'image/heic';
  return 'image/jpeg';
}

const CATEGORY_KEYS = [
  'water_supply',
  'roads_potholes',
  'street_light',
  'garbage_waste',
  'drainage_sewer',
  'other',
];

const LANG_NAMES = { en: 'English', mr: 'Marathi (मराठी)', hi: 'Hindi (हिंदी)' };

function buildSystemPrompt(language) {
  const langName = LANG_NAMES[language] || 'English';
  return `You are Takrar Sahayak, the AMC grievance intake assistant. Reply ONLY in ${langName}.
Gather: category (one of: ${CATEGORY_KEYS.join('|')}), description, location_text, duration_or_details. Ask ONE question at a time.
latitude/longitude: only if citizen names a known Amravati area (lat 20.92-20.96, lng 77.74-77.82), else null.

CRITICAL INSTRUCTION WHEN ALL DETAILS (category + description + location_text) ARE GATHERED:
1. Set ready_to_submit: true
2. Write a 2-sentence English summary in the "summary" field.
3. In the "reply" field:
   - Thank the citizen for providing the details.
   - State that the summary of their complaint regarding [topic/category] has been generated (DO NOT use "recorded and generated" together, use only "generated").
   - Clearly guide the citizen to review the summary in the side panel and click on the "Submit Grievance" / "तक्रार दाखल करा" / "शिकायत दर्ज करें" button to officially file and submit the grievance to municipal officers.
   - DO NOT say "your complaint has been resolved" or "it has already been submitted/addressed". Emphasize that clicking the Submit button is required to finalize submission.

Example ready_to_submit reply formats:
- If English: "Thank you for the details! The summary of your complaint regarding [topic/category] has been generated. Please review the details in the summary panel and click on the 'Submit Grievance' option to officially file your grievance."
- If Marathi: "माहिती दिल्याबद्दल धन्यवाद! आपल्या [विषय/तक्रार] बाबतच्या तक्रारीचा सारांश तयार करण्यात आला आहे. कृपया बाजूला दिलेला सारांश तपासा आणि आपली तक्रार अधिकृतपणे दाखल करण्यासाठी 'तक्रार दाखल करा' (Submit Grievance) या पर्यायावर क्लिक करा."
- If Hindi: "विवरण देने के लिए धन्यवाद! आपके [विषय/शिकायत] संबंधित शिकायत का सारांश तैयार कर लिया गया है। कृपया सारांश की जांच करें और अपनी शिकायत आधिकारिक रूप से दर्ज करने के लिए 'शिकायत दर्ज करें' (Submit Grievance) विकल्प पर क्लिक करें।"

IMPORTANT: Your entire response must be a single valid JSON object with NO markdown fences, NO extra text before or after.
Output format (all fields required): {"reply":"...","category":null,"description":null,"location_text":null,"latitude":null,"longitude":null,"duration_or_details":null,"summary":null,"ready_to_submit":false}`;
}

// POST /api/chatbot/message
// body: { message: string, history: [{role:'user'|'assistant', text:string}], language: 'en'|'mr'|'hi' }
router.post('/message', authOptional, async (req, res) => {
  const { message, history = [], language = 'en' } = req.body || {};
  if (!message || typeof message !== 'string') {
    return res.status(400).json({ error: 'message is required' });
  }
  if (rawKeys.length === 0) {
    return res.status(503).json({
      error: 'AI assistant is not configured. Set GEMINI_API_KEYS in server/.env',
    });
  }

  // Gemini's `contents` array must start with a "user" turn and use "model"
  // (not "assistant") for the AI's turns. The client's chat log can start
  // with a hardcoded assistant greeting (never actually generated by the
  // model) and may already include the citizen's latest message, so both
  // need to be normalized here rather than trusted as-is.
  const firstUserIdx = history.findIndex((h) => h.role === 'user');
  const trimmedHistory = firstUserIdx === -1 ? [] : history.slice(firstUserIdx);

  const historyTurns = trimmedHistory.slice(-4).map((h) => ({
    role: h.role === 'assistant' ? 'model' : 'user',
    text: h.text,
  }));

  // Avoid sending the new message twice if the client already included it
  // as the last entry of `history`.
  const last = historyTurns[historyTurns.length - 1];
  if (last && last.role === 'user' && last.text === message) {
    historyTurns.pop();
  }

  // Collapse any remaining consecutive same-role turns (defensive; Gemini
  // expects alternating roles too).
  const turns = [];
  for (const t of [...historyTurns, { role: 'user', text: message }]) {
    const prev = turns[turns.length - 1];
    if (prev && prev.role === t.role) {
      prev.text += `\n${t.text}`;
    } else {
      turns.push({ ...t });
    }
  }

  const contents = turns.map((t) => ({ role: t.role, parts: [{ text: t.text }] }));

  let lastErr = null;
  for (let attempt = 0; attempt < rawKeys.length; attempt++) {
    const client = nextClient();
    keyIndex++;
    try {
      const resp = await client.models.generateContent({
        model: GEMINI_MODEL,
        contents,
        config: {
          systemInstruction: buildSystemPrompt(language),
          responseMimeType: 'application/json',
          maxOutputTokens: 220,
          temperature: 0.1,
        },
      });
      const raw = (resp.text || '').trim();
      // Strip markdown code fences if present (```json ... ``` or ``` ... ```)
      const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/,'').trim();
      let parsed;
      try {
        parsed = JSON.parse(cleaned);
      } catch (_e) {
        // Try to extract the first JSON object from the response (handles garbage prefix/suffix)
        const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
          try {
            parsed = JSON.parse(jsonMatch[0]);
          } catch (_e2) {
            parsed = null;
          }
        }
        if (!parsed) {
          // Last resort: if response looks like random/garbled text, return a safe fallback message
          const looksGarbled = !cleaned || /^[^{"a-zA-Z\u0900-\u097F\u0020-\u007E]{5,}/.test(cleaned);
          const safeReply = looksGarbled
            ? (language === 'mr' ? 'क्षमा करा, कृपया पुन्हा प्रयत्न करा.' : language === 'hi' ? 'क्षमा करें, कृपया पुनः प्रयास करें।' : 'Sorry, I did not understand. Please try again.')
            : cleaned;
          parsed = { reply: safeReply, category: null, description: null, location_text: null, latitude: null, longitude: null, duration_or_details: null, summary: null, ready_to_submit: false };
        }
      }
      // Validate lat/lng are numbers within Amravati bounding box (defense against hallucination)
      if (parsed.latitude != null || parsed.longitude != null) {
        const lat = parseFloat(parsed.latitude);
        const lng = parseFloat(parsed.longitude);
        if (isNaN(lat) || isNaN(lng) || lat < 20.8 || lat > 21.1 || lng < 77.5 || lng > 78.0) {
          parsed.latitude = null;
          parsed.longitude = null;
        }
      }

      // If citizen message contains exact GPS coordinates (e.g. "Badnera Road, Amravati (GPS: 20.93201, 77.75231)")
      const gpsMatch = message.match(/(?:GPS|gps)[:\s]+([0-9.]+)[,\s]+([0-9.]+)/i);
      if (gpsMatch) {
        const lat = parseFloat(gpsMatch[1]);
        const lng = parseFloat(gpsMatch[2]);
        if (!isNaN(lat) && !isNaN(lng) && lat >= 20.8 && lat <= 21.1 && lng >= 77.5 && lng <= 78.0) {
          parsed.latitude = lat;
          parsed.longitude = lng;
          if (!parsed.location_text) {
            parsed.location_text = message.replace(/\s*\(?(?:GPS|gps)[:\s]+[0-9.]+[,\s]+[0-9.]+\)?/i, '').trim();
          }
        }
      }

      // If ready_to_submit is true, ensure reply does not falsely claim the issue is already submitted/resolved and clearly guides the user to click the Submit button
      if (parsed.ready_to_submit && parsed.reply) {
        parsed.reply = parsed.reply
          .replace(/recorded and generated/gi, 'generated')
          .replace(/generated and recorded/gi, 'generated')
          .replace(/नोंदवला आणि तयार केला/gi, 'तयार केला')
          .replace(/दर्ज और तैयार/gi, 'तैयार');

        const hasSubmitPrompt = /(?:submit|दाखल|नोंदव|दर्ज|button|बटण|बटन|click|क्लिक)/i.test(parsed.reply);
        if (!hasSubmitPrompt) {
          if (language === 'mr') {
            parsed.reply += `\n\n📌 तक्रारीचा सारांश तयार करण्यात आला आहे. कृपया बाजूला दिलेला सारांश तपासून 'तक्रार दाखल करा' (Submit Grievance) या बटणावर क्लिक करा.`;
          } else if (language === 'hi') {
            parsed.reply += `\n\n📌 आपकी शिकायत का सारांश तैयार कर लिया गया है। कृपया सारांश की जांच करें और 'शिकायत दर्ज करें' (Submit Grievance) बटन पर क्लिक करें।`;
          } else {
            parsed.reply += `\n\n📌 The summary of your complaint has been generated. Please review the details in the summary panel and click on 'Submit Grievance' to officially submit your complaint.`;
          }
        }
      }
      return res.json(parsed);
    } catch (err) {
      lastErr = err;
      // try next key on failure (rate limit / auth / transient)
      continue;
    }
  }
  console.error('Chatbot AI error (all keys failed):', lastErr?.message);
  return res.status(502).json({ error: 'AI assistant is temporarily unavailable. Please try again.' });
});

// POST /api/chatbot/analyze-image
// body: { imagePath: string, language: 'en'|'mr'|'hi' }
router.post('/analyze-image', authOptional, async (req, res) => {
  const { imagePath, language = 'en' } = req.body || {};
  if (!imagePath || typeof imagePath !== 'string') {
    return res.status(400).json({ error: 'imagePath is required' });
  }
  if (rawKeys.length === 0) {
    return res.status(503).json({ error: 'AI assistant is not configured. Set GEMINI_API_KEYS in server/.env' });
  }

  const safeFilename = path.basename(imagePath);
  const fullPath = path.join(__dirname, '..', '..', 'uploads', safeFilename);
  if (!fs.existsSync(fullPath)) {
    return res.status(404).json({ error: 'Image file not found' });
  }

  const mimeType = getMimeType(fullPath);
  const imageBase64 = fs.readFileSync(fullPath).toString('base64');
  const langName = LANG_NAMES[language] || 'English';

  const promptText = `You are an AI civic grievance specialist for Amravati Municipal Corporation (AMC).
Analyze this uploaded citizen photograph and identify the municipal civic problem (e.g., potholes, broken road, leaking water pipe, broken streetlight, garbage heap, overflowing drain/sewer, etc.).
Determine:
1. is_civic_issue: boolean (true if it represents a city grievance)
2. category: one of ["water_supply", "roads_potholes", "street_light", "garbage_waste", "drainage_sewer", "other"]
3. severity: one of ["low", "normal", "high", "urgent"]
4. issue_title: short concise title in English
5. description: 1-2 sentence detailed objective description in English
6. suggested_message: a polite 1-2 sentence complaint message written naturally in ${langName} that the citizen can send to file this complaint.

Output ONLY a single valid JSON object with NO markdown formatting, NO backticks:
{"is_civic_issue": true, "category": "roads_potholes", "severity": "high", "issue_title": "...", "description": "...", "suggested_message": "..."}`;

  let lastErr = null;
  for (let attempt = 0; attempt < rawKeys.length; attempt++) {
    const client = nextClient();
    keyIndex++;
    try {
      const resp = await client.models.generateContent({
        model: GEMINI_MODEL,
        contents: [
          {
            role: 'user',
            parts: [
              {
                inlineData: {
                  mimeType,
                  data: imageBase64,
                },
              },
              { text: promptText },
            ],
          },
        ],
        config: {
          responseMimeType: 'application/json',
          maxOutputTokens: 500,
          temperature: 0.2,
        },
      });

      const raw = (resp.text || '').trim();
      const cleaned = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();
      let parsed;
      try {
        parsed = JSON.parse(cleaned);
      } catch (_e) {
        const match = cleaned.match(/\{[\s\S]*\}/);
        if (match) parsed = JSON.parse(match[0]);
      }

      if (!parsed) {
        return res.status(500).json({ error: 'Could not parse image analysis output.' });
      }

      if (!CATEGORY_KEYS.includes(parsed.category)) {
        parsed.category = 'other';
      }

      return res.json(parsed);
    } catch (err) {
      lastErr = err;
      continue;
    }
  }

  console.error('Image AI Vision error (all keys failed):', lastErr?.message);
  return res.status(502).json({ error: 'AI image analysis is temporarily unavailable.' });
});

module.exports = router;
