-- ==============================================================================
-- MAZHI AMRAVATI CIVIC GRIEVANCE REDRESSAL PLATFORM
-- PostgreSQL + PostGIS Database Schema for Supabase
-- ==============================================================================

-- 1. Enable PostGIS Spatial Extension
CREATE EXTENSION IF NOT EXISTS postgis SCHEMA extensions;

-- Set search path to include public and extensions
SET search_path TO public, extensions;

-- 2. Departments Table (Multi-Lingual Support)
CREATE TABLE IF NOT EXISTS public.departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_mr TEXT,
  name_hi TEXT,
  category_keys TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Users Table (Citizens, Department Officers, System Admins)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('citizen','officer','admin')) DEFAULT 'citizen',
  department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
  language TEXT DEFAULT 'en',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Complaints Table (With PostGIS Point & JSONB Transcripts)
CREATE TABLE IF NOT EXISTS public.complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id TEXT UNIQUE NOT NULL,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  guest_name TEXT,
  guest_contact TEXT,
  category TEXT NOT NULL,
  description TEXT NOT NULL,
  summary TEXT,
  language TEXT DEFAULT 'en',
  location_text TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  geom GEOMETRY(Point, 4326),
  ward TEXT,
  photos JSONB DEFAULT '[]'::jsonb,
  resolution_photo TEXT,
  rating INT CHECK(rating BETWEEN 1 AND 5),
  rating_feedback TEXT,
  voice_note TEXT,
  department_id BIGINT REFERENCES public.departments(id) ON DELETE SET NULL,
  assigned_officer_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN ('submitted','assigned','in_progress','resolved','rejected')),
  priority TEXT DEFAULT 'normal' CHECK(priority IN ('low','normal','high','urgent')),
  chat_transcript JSONB DEFAULT '[]'::jsonb,
  upvote_count INT DEFAULT 0,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Spatial Index for Fast Geofencing & Heatmap Queries
CREATE INDEX IF NOT EXISTS idx_complaints_geom ON public.complaints USING GIST(geom);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON public.complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_dept ON public.complaints(department_id);
CREATE INDEX IF NOT EXISTS idx_complaints_created ON public.complaints(created_at DESC);

-- 6. Trigger to Auto-Populate PostGIS `geom` Point from Latitude & Longitude
CREATE OR REPLACE FUNCTION public.update_complaint_geom()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.latitude IS NOT NULL AND NEW.longitude IS NOT NULL THEN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326);
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_complaint_geom ON public.complaints;
CREATE TRIGGER trg_complaint_geom
BEFORE INSERT OR UPDATE ON public.complaints
FOR EACH ROW EXECUTE FUNCTION public.update_complaint_geom();

-- 7. Audit Trail History Table
CREATE TABLE IF NOT EXISTS public.complaint_status_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES public.complaints(id) ON DELETE CASCADE,
  status TEXT NOT NULL,
  note TEXT,
  changed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Community Upvotes
CREATE TABLE IF NOT EXISTS public.complaint_upvotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT REFERENCES public.complaints(id) ON DELETE CASCADE,
  voter_ip TEXT,
  user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(complaint_id, voter_ip)
);

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================

-- Seed Municipal Departments
INSERT INTO public.departments (name, name_mr, name_hi, category_keys) VALUES
  ('Water Supply Department', 'पाणीपुरवठा विभाग', 'जल आपूर्ति विभाग', 'water_supply'),
  ('Roads & Potholes Department', 'रस्ते व खड्डे विभाग', 'सड़क एवं गड्ढे विभाग', 'roads_potholes'),
  ('Street Lighting Department', 'स्ट्रीट लाईट विभाग', 'स्ट्रीट लाइट विभाग', 'street_light'),
  ('Solid Waste Management Department', 'कचरा व्यवस्थापन विभाग', 'ठोस अपशिष्ट प्रबंधन विभाग', 'garbage_waste'),
  ('Drainage & Sewerage Department', 'गटार / निचरा विभाग', 'जल निकासी एवं सीवरेज विभाग', 'drainage_sewer'),
  ('General Administration Department', 'सर्वसाधारण प्रशासन विभाग', 'सामान्य प्रशासन विभाग', 'other')
ON CONFLICT DO NOTHING;

-- Seed Default Super Admin (Password: Admin@123)
INSERT INTO public.users (name, email, phone, password_hash, role) VALUES
  ('Super Admin', 'admin@amravati.gov.in', '9999999999', '$2a$10$Z3U6L09Xj8W8Jg7sWnZJweYfW8X2qG0qX9X2qG0qX9X2qG0qX9X2q', 'admin')
ON CONFLICT (email) DO NOTHING;

-- ==============================================================================
-- HELPER SPATIAL STORED PROCEDURES
-- ==============================================================================

-- 1. Find Nearby Complaints within Radius (for Duplicate Detection)
CREATE OR REPLACE FUNCTION get_nearby_complaints(
  p_lat DOUBLE PRECISION,
  p_lng DOUBLE PRECISION,
  p_radius_meters INT DEFAULT 100
)
RETURNS TABLE (
  id BIGINT,
  public_id TEXT,
  category TEXT,
  status TEXT,
  distance_meters DOUBLE PRECISION
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.public_id,
    c.category,
    c.status,
    ST_Distance(
      c.geom::geography,
      ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography
    ) AS distance_meters
  FROM complaints c
  WHERE c.geom IS NOT NULL
    AND c.status != 'resolved'
    AND ST_DWithin(
      c.geom::geography,
      ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326)::geography,
      p_radius_meters
    )
  ORDER BY distance_meters ASC;
END;
$$ LANGUAGE plpgsql;
